SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) TOTAL_SALES
FROM BOOK
INNER JOIN AUTHOR USING (AUTHOR_ID)
INNER JOIN BOOK_SALES USING (BOOK_ID)
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;

# SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, (SALES * PRICE) TOTAL_SALES
# FROM BOOK
# INNER JOIN AUTHOR USING (AUTHOR_ID)
# INNER JOIN BOOK_SALES USING (BOOK_ID)
# WHERE DATE_FORMAT(SALES_DATE, '%Y-%d') = '2022-01'
# GROUP BY CATEGORY
# ORDER BY CATEGORY;